version: "3.7"

services:
  db:
    image: postgres:12-alpine
    container_name: "service-databaase"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - service-database
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "service-rest-api"
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DB=$DB_DB
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - SSL_MODE=$SSL_MODE
      - JWT_KEY=$JWT_KEY
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - service

volumes:
  database_postgres:

networks:
  galactic-trade:
    driver: bridge